title: Minha página no GitHub
author: Eduardo Moura
email: edurdormoura78@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  
  Site sendo utilizado como ferramenta de aprendizado do GitHub.
  
  teste
 
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

